#!/usr/bin/env python3
"""
Generate Arduino material snippet headers from the existing data/store_index.json
without scraping the store. This mirrors the scraper output so Arduino sketches,
Store Index, and JSON stay in sync.

Usage:
    python scripts/generate_material_snippets.py

Prereq: data/store_index.json must exist (produced by the scraper or provided).
"""
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
STORE_INDEX_JSON = ROOT / "data" / "store_index.json"
ARDUINO_SNIPPETS = [
    ROOT / "arduino" / "RFID_Bambu_lab_reader" / "generated" / "materials_snippet.h",
    ROOT / "arduino" / "RFID_Bambu_lab_reader_OLED" / "generated" / "materials_snippet.h",
]


def esc(val: Optional[str]) -> str:
    """Return ASCII-safe, escaped string for inclusion in C string literals."""
    if not val:
        return ""
    return (
        str(val)
        .encode("ascii", "ignore")
        .decode("ascii")
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
    )


def load_records() -> List[Dict[str, Any]]:
    if not STORE_INDEX_JSON.exists():
        raise FileNotFoundError(f"Missing {STORE_INDEX_JSON}; run scraper or supply the file.")
    data = json.loads(STORE_INDEX_JSON.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"Expected a JSON array in {STORE_INDEX_JSON}")
    return data


def build_lines(records: List[Dict[str, Any]]) -> List[str]:
    lines = [
        "// Generated by scripts/generate_material_snippets.py from data/store_index.json.",
        "// materialId not scraped; left blank. variantId comes from store feed when present. productUrl from store feed.",
    ]
    for rec in sorted(records, key=lambda r: (r.get("code") or "", r.get("color") or "")):
        code = esc(rec.get("code"))
        name = esc(rec.get("name"))
        color = esc(rec.get("color"))
        variant = esc(rec.get("variantId"))
        product_url = esc(rec.get("productUrl"))
        lines.append(f'    {{"", "{variant}", "{code}", "{name}", "{color}", "{product_url}"}},')
    return lines


def write_snippets(lines: List[str]) -> None:
    content = "\n".join(lines) + "\n"
    for path in ARDUINO_SNIPPETS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote Arduino snippet: {path.relative_to(ROOT)}")


def main() -> int:
    try:
        records = load_records()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    lines = build_lines(records)
    write_snippets(lines)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
